name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: [enhancement, triage]
assignees:
  - tweakch
body:
  - type: markdown
    attributes:
      value: |
        <!-- You have an idea on how to improve blockdrost-dotnet? Awesome! Please tell us about it... -->
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/blockfrost/blockfrost-dotnet/blob/main/CODE_OF_CONDUCT.md)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true