name: ci build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [windows-latest, ubuntu-latest, ubuntu-18.04, macOS-latest, macos-11]
    env:
      BFCLI_NETWORK: testnet
      BFCLI_API_KEY: ${{ secrets.BFCLI_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
